
---@class Attack
---
---How is the attack placed in the world?
---
---@field radius number
---@field arc number
---@field projectile string
---@field z number
---@field height number
---
---Who gets hit by this attack?
---@field hitslayers integer
---
---What happens to them on impact?
---
---@field damage number
---@field opponentstateonhit string
---@field opponentstateonfinalhit string
---TODO the below could be part of fighter data or damage states
---@field opponentstun integer
---@field mercyinvuln integer
---@field hurtparticle string
---@field hurtcolorcycle string
---@field pushbackspeed number
---@field launchspeed number
---
---What happens to me on impact?
---
---@field selfstun integer
---@field selfstateonhit string
---@field selfstateonhitopponent string?
---@field selfstateonhitboundary string?
---@field selfstateonguard string?
---
---What else happens on impact?
---@field hitspark string
---@field hitsound string
---@field guardhitspark string
---@field guardhitsound string
---
---Other properties
---@field deflectsprojectileatopponent boolean
---@field canjuggle boolean